import type { Metadata } from 'next'
import { Poppins } from 'next/font/google';
import './globals.css'
import {cn} from '@/lib/utils'

const fontPoppins = Poppins({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return(
    <html lang="pt-br">
      <body className={cn(
        "min-h-screen",
        fontPoppins.className
        )}>
          {children}
        </body>
    </html>
  );
}