import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Ubuntu } from 'next/font/google';

import './globals.css'
import {cn} from '@/lib/utils'

const fontUbuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={cn(
        "min-h-screen",
        fontUbuntu.className
        )}>{children}</body>
    </html>
  )
}
